use axum::routing::{delete, get, post};
use axum::Router;
use std::sync::Arc;

use crate::config::Config;
use crate::handlers::{config_api, health, models, pools, proxy};
use crate::metrics;
use crate::middleware::audit::AuditLayer;
use crate::middleware::auth::AuthLayer;
use crate::middleware::metrics::MetricsLayer;
use crate::openapi;
use crate::queue::publisher::WorkPublisher;
use crate::state::config_epoch::ConfigEpoch;
use crate::state::demand_tracker::DemandTracker;
use crate::state::model_registry::ModelRegistry;
use crate::state::pool_manager::PoolManager;
use crate::state::worker_registry::WorkerRegistry;

pub struct AppState {
    pub registry: Arc<WorkerRegistry>,
    pub config: Arc<Config>,
    pub model_registry: Arc<ModelRegistry>,
    pub pool_manager: Arc<PoolManager>,
    pub work_publisher: Option<Arc<WorkPublisher>>,
    pub demand_tracker: Arc<DemandTracker>,
    /// Monotonic view of the furthest-known control-plane epoch. Written by
    /// bootstrap, the NATS delta handler, and the epoch poller; read by
    /// `GET /v1/configs/models/{id}/status` and metrics (`sie_gateway_config_epoch`).
    pub config_epoch: ConfigEpoch,
}

pub fn create_router(state: Arc<AppState>, config: Arc<Config>) -> Router {
    Router::new()
        // Status page
        .route("/", get(health::status_page))
        // Health endpoints
        .route("/healthz", get(health::healthz))
        .route("/readyz", get(health::readyz))
        .route("/health", get(health::health))
        // Metrics endpoint
        .route("/metrics", get(metrics_handler))
        // API description
        .route("/openapi.json", get(openapi::openapi_json))
        // Models endpoints. `{*model}` accepts slash-bearing IDs.
        .route("/v1/models", get(models::get_models))
        .route("/v1/models/{*model}", get(models::get_model))
        // Pool endpoints
        .route("/v1/pools", post(pools::create_pool))
        .route("/v1/pools", get(pools::list_pools))
        .route("/v1/pools/{name}", get(pools::get_pool))
        .route("/v1/pools/{name}", delete(pools::delete_pool))
        .route("/v1/pools/{name}/renew", post(pools::renew_pool))
        // Config API endpoints. Gateway is read-only; config writes go to
        // `packages/sie_config`. `POST /v1/configs/models` is not
        // registered, so axum returns `405 Method Not Allowed` for write
        // attempts against the gateway (no shim, no redirect body).
        //
        // The `{*id}` wildcard exists because model IDs commonly contain
        // slashes (e.g. `BAAI/bge-m3`). A trailing `/status` suffix on
        // the same wildcard is disambiguated inside
        // `get_model_config_or_status` — see that handler's doc comment
        // for the routing contract.
        .route("/v1/configs/models", get(config_api::get_model_configs))
        .route(
            "/v1/configs/models/{*id}",
            get(config_api::get_model_config_or_status),
        )
        .route("/v1/configs/bundles", get(config_api::get_bundle_configs))
        .route(
            "/v1/configs/bundles/{id}",
            get(config_api::get_bundle_config),
        )
        .route("/v1/configs/resolve", post(config_api::resolve_config))
        // WebSocket cluster status
        .route("/ws/cluster-status", get(health::ws_cluster_status))
        .route("/v1/embeddings", post(proxy::proxy_openai_embeddings))
        // Proxy endpoints - use wildcard for model path
        .route("/v1/encode/{*model}", post(proxy::proxy_encode))
        .route("/v1/score/{*model}", post(proxy::proxy_score))
        .route("/v1/extract/{*model}", post(proxy::proxy_extract))
        .layer(AuditLayer::new())
        .layer(AuthLayer::new(config))
        // MetricsLayer is appended last so it becomes the outermost
        // layer on the inbound side: it observes the total time and
        // final status of the full stack (including auth 401/403s and
        // any response generated by axum itself, e.g. 404 Not Found for
        // unmatched routes). This is what closes the "only success
        // path was counted" gap that used to live inside proxy.rs.
        .layer(MetricsLayer::new())
        .with_state(state)
}

#[utoipa::path(
    get,
    path = "/metrics",
    tag = "observability",
    responses((status = 200, description = "Prometheus metrics", body = String, content_type = "text/plain"))
)]
pub(crate) async fn metrics_handler(
    axum::extract::State(state): axum::extract::State<Arc<AppState>>,
) -> impl axum::response::IntoResponse {
    // Update worker gauges before serving
    let workers = state.registry.workers().await;
    let snapshots: Vec<metrics::WorkerSnapshot> = workers
        .values()
        .map(|w| metrics::WorkerSnapshot {
            name: w.name.clone(),
            machine_profile: w.machine_profile.clone(),
            bundle: w.bundle.clone(),
            queue_depth: w.queue_depth,
            memory_used_bytes: w.memory_used_bytes,
            healthy: w.healthy(),
        })
        .collect();
    metrics::update_worker_metrics(&snapshots);

    // Clear PENDING_DEMAND for GPUs that now have healthy workers
    let healthy_gpus: std::collections::HashSet<String> = snapshots
        .iter()
        .filter(|w| w.healthy && !w.machine_profile.is_empty())
        .map(|w| w.machine_profile.to_lowercase())
        .collect();
    metrics::clear_fulfilled_demand(&healthy_gpus, &state.demand_tracker);

    let model_workers = state.registry.get_models().await;
    let model_counts: std::collections::HashMap<String, usize> = model_workers
        .into_iter()
        .map(|(name, urls)| (name, urls.len()))
        .collect();
    metrics::update_model_metrics(&model_counts);

    // Update pool lease metrics
    let pools = state.pool_manager.list_pools().await;
    metrics::update_pool_metrics(&pools);

    let encoder = prometheus::TextEncoder::new();
    let metric_families = metrics::REGISTRY.gather();
    let mut buffer = Vec::new();
    prometheus::Encoder::encode(&encoder, &metric_families, &mut buffer).unwrap();
    let buffer = String::from_utf8(buffer).unwrap();

    (
        axum::http::StatusCode::OK,
        [(
            axum::http::header::CONTENT_TYPE,
            "text/plain; version=0.0.4; charset=utf-8",
        )],
        buffer,
    )
}
